name: flutteradal
description: Plugin to use the ADAL packages from Android & IOS.
version: 1.0.2
author:  Marius Schmack <schmackmarius@gmail.com>
homepage: https://github.com/peyter213/Flutter-Adal

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.example.flutteradal
    pluginClass: FlutteradalPlugin